### PR TITLE
basic FE dependencies

### PR DESCRIPTION
**Pull request by melanieso**
Intalled some basic FE dependencies, mostly for components: 

- material-ui
- styled-components
- prop-types
- lodash

### CODE REVIEW

**Review by nickw444 — CHANGES_REQUESTED** [review]
If you are using yarn, then a `package-lock.json` is not necessary as that is used by `npm` only.

**Comment by jjccharles** [comment]
Yep as nick said, lets try and stick to using yarn only so the package-lock.json shouldn't be required

**Review by jjccharles — CHANGES_REQUESTED** [review]
Update yarn.lock to match new deps if it hasnt been and remove package-lock.json

**Comment by melanieso** [comment]
oop my bad, done i think 💪

**Review by nickw444 — APPROVED** [review]

**Review by jjccharles — APPROVED** [review]

**Pull request merged**
